### PR TITLE
redirect to jupyter.org/try

### LINKED ISSUE #21: Replace tmpnb.org with links to mybinder.org
Right now, we are running try.jupyter.org (tmpnb.org) with the *massive* docker image containing Python, R, Julia, Haskell, etc. [here](https://github.com/jupyter/docker-demo-images). The main reason we have this kitchen-sink image is that tmpnb only runs with one image. With mybinder.org, a collection of links to different binders can solve this problem without having to run a dedicated service

Problems right now:

- deploying tmpnb instances is a bit of a pain
- we have one massive image to update
- I might be the only person keeping tmpnb.org alive

Potential downsides with switching to binder:

- Binder has its own infrastructure and hosting costs. Currently, tmpnb.org has ~200 concurrent users at any given time. If all of these folks moved over to mybinder.org, this would ~double the total binder traffic. It may not be appropriate for Jupyter as a whole to burden binder with this cost.

## Proposal

My proposal is to switch try.jupyter.org to a collection of binderable repos, demoing basic functionality and retire docker-demo-images (jupyter/demo) entirely.

Steps:

1. build a few demo repos
2. update try.jupyter.org to redirect to the binder link (OR: serve the landing page), rather than iframing tmpnb.org
3. shutdown or reduce tmpnb.org
4. archive https://github.com/jupyter/docker-demo-images

### PR DESCRIPTION
**Pull request by minrk**
currently the list only contains a link to ipython-in-depth, but we can add more as they come.

requires https://github.com/ipython/ipython-in-depth/pull/54 before the link will work

closes #21

Note: this page could live on the regular jupyter.org site, and we could redirect try.jupyter.org to jupyter.org/try.html. That might result in less duplication.

### CODE REVIEW

**Comment by minrk** [comment]
Added R and Julia as links to binder-examples repos. We should replace these with other demos, but they work for now.

**Comment by minrk** [comment]
Preview of the page with the Python link highlighted:

screen shot 2018-02-26 at 12 17 38

**Comment by Carreau** [comment]
cc @tgeorgeux @ellisonbg

**Comment by ellisonbg** [comment]
Thanks @minrk for working on this. I like the idea of having a try page on the website and redirecting `try.jupyter.org` to that. In the current PR, is this on a separate page, or the home page? Can you post a screenshot of the entire page to give more context?

**Comment by minrk** [comment]
This PR is to try.jupyter.org. I'll do another PR adding this to the regular website, since the pattern is very similar to what we already have there for documentation. Then this PR will be replaced with a simple redirect to `jupyter.org/try`.

**Comment by minrk** [comment]
OK, should be set. This PR now causes try.jupyter.org to be a simple redirect to jupyter.org/try. https://github.com/jupyter/jupyter.github.io/pull/270 adds the Binder links to jupyter.org/try.

Merge order:

1. https://github.com/ipython/ipython-in-depth/pull/54 (ipython-in-depth works on Binder)
2. https://github.com/jupyter/jupyter.github.io/pull/270 (add jupyter.org/try)
3. this PR (redirect try.jupyter.org to jupyter.org/try)
4. (not a PR) shutdown tmpnb.org servers

**Comment by rgbkrk** [comment]
Woo!

**Pull request merged**
