### PR TITLE
Rely on top-level redirector

### PR DESCRIPTION
**Pull request by rgbkrk**
tmp54 is dead, long live the king

https://github.com/jupyter/help/issues/88

### CODE REVIEW

**Comment by rgbkrk** [comment]
Disabling Travis for this repo, as it's not necessary.

**Comment by rgbkrk** [comment]
Welp, tmp57 doesn't have the right content security policy set.

> Refused to display 'https://tmp57.tmpnb.org/user/lABDPwkTgydM/tree' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://_.jupyter.org https://jupyter.github.io https://_.tmpnb.org".

.________.

**Comment by minrk** [comment]
@rgbkrk did you fix something manually? it seems to be working for me on all workers, including tmp57.

**Comment by rgbkrk** [comment]
Nope, haven't changed anything. Only reported back here.

**Comment by minrk** [comment]
Is it working for you? Safari and Chrome both appear to work from here.

**Comment by rgbkrk** [comment]
screen shot 2016-10-07 at 9 14 22 am

**Comment by rgbkrk** [comment]
It does the redirection right, but then when I get to the underlying notebook server the CSP rejects it. Both for tmp56 and tmp57.

**Comment by minrk** [comment]
weird...

screen shot 2016-10-07 at 15 17 46

Chrome version?

**Comment by rgbkrk** [comment]
Version 53.0.2785.116 (64-bit)

Looks like an update needs to be done for me.

**Comment by rgbkrk** [comment]
And I've updated to Version 53.0.2785.143 (64-bit). Still a problem.

**Comment by minrk** [comment]
I've got 54.0.2840.50 (beta channel), so maybe that's relevant. The setting doesn't appear to be wrong, though.

Can you check in incognito and/or other browsers?

**Comment by rgbkrk** [comment]
screen shot 2016-10-07 at 9 32 00 am

**Pull request merged**
